[package]
name = "agent-collector"
version = "0.1.0"
edition = "2021"

[dependencies]
monitoring-core = { path = "../core"  }
log = "0.4"
psutil = { version = "3.2", default-features = false, features = ["cpu", "memory"]}
