[package]
name = "agent-config"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
uuid = { version = "1.1", features = ["v4"]  }

[features]
default = ["web", "webhooks"]
web = []
webhooks = []
