[package]
name = "monitoring-agent"
version = "0.1.0"
edition = "2021"

[dependencies]
monitoring-core = { path = "../core"  }
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
psutil = { version = "3.2", default-features = false, features = ["cpu", "memory"]}
actix-web = "4.1"
